# Linking Hex Urban Form Data to Polygons

Creating table with multiple urban form measures

```sql
DROP TABLE IF EXISTS out_data_hex_all;
CREATE TABLE out_data_hex_all AS (
    SELECT 
        out_data_hex_transit2018.hexid, 
        coalesce(out_data_hex_business2016.business2016,0) as business2016,
        coalesce(out_data_hex_pop2016.pop2016,0) as pop2016,
        coalesce(out_data_hex_emp2016.emp2016,0) as emp2016,
        coalesce(out_data_hex_int3way2018.int3way,0) as int3way,
        coalesce(out_data_hex_int4way2018.int4way,0) as int4way,
        coalesce(out_data_hex_osmwalkedge2018.edge_length,0) as walk_edge_length,
        coalesce(out_data_hex_transit2018.n_per_hour,0) as transit_n_per_hour
    FROM
    out_data_hex_transit2018 
    LEFT OUTER JOIN out_data_hex_pop2016 
    ON (out_data_hex_transit2018.hexid = out_data_hex_pop2016.hexid)
    LEFT OUTER JOIN out_data_hex_emp2016 
    ON (out_data_hex_transit2018.hexid = out_data_hex_emp2016.hexid)
    LEFT OUTER JOIN out_data_hex_int3way2018 
    ON (out_data_hex_transit2018.hexid = out_data_hex_int3way2018.hexid)
    LEFT OUTER JOIN out_data_hex_int4way2018 
    ON (out_data_hex_transit2018.hexid = out_data_hex_int4way2018.hexid)
    LEFT OUTER JOIN out_data_hex_osmwalkedge2018 
    ON (out_data_hex_transit2018.hexid = out_data_hex_osmwalkedge2018.hexid)
    LEFT OUTER JOIN out_data_hex_business2016 
    ON (out_data_hex_transit2018.hexid = out_data_hex_business2016.hexid)
);

\COPY out_data_hex_all TO 'out_data_hex_all.csv' WITH (FORMAT CSV, HEADER);

```

## Linking to 2016 census dissemination areas (DA)

```sql
-- create spatial index on DA boundaries

DROP INDEX IF EXISTS zones_da16_gix;
CREATE INDEX zones_da16_gix ON zones_da16 USING GIST (geom);

-- intersect the DA boundaries with the hex grid

CREATE TABLE temp_int_hex_da AS
(
SELECT
hex_grid_200m.id AS hexid,
zones_da16.dauid AS dauid,
34641.0161513719 AS area_full,
ST_Intersection(hex_grid_200m.geom,zones_da16.geom) AS geom
FROM
zones_da16 INNER JOIN hex_grid_200m ON ST_Intersects(hex_grid_200m.geom,zones_da16.geom)
);

-- update area of intersected geoms

ALTER TABLE temp_int_hex_da ADD COLUMN area_int double precision;
UPDATE temp_int_hex_da SET area_int = ST_AREA(geom);

ALTER TABLE temp_int_hex_da ADD COLUMN area_ratio double precision;
UPDATE temp_int_hex_da SET area_ratio = area_int / area_full;

-- create weights table for apportioning

CREATE TABLE weights_hex_da AS
(
SELECT
hexid,
dauid,
sum(area_ratio) AS weight
FROM
temp_int_hex_da
GROUP BY dauid, hexid
ORDER BY dauid, hexid
);

DROP TABLE temp_int_hex_da;

-- join data and apportion to boundaries

DROP TABLE IF EXISTS out_data_da;
CREATE TABLE out_data_da AS (
    WITH temp_weight_join AS (
        SELECT
        weights_hex_da.dauid AS dauid,
        weights_hex_da.hexid AS hexid,
        weights_hex_da.weight AS weight,
        out_data_hex_all.pop2016 AS pop2016,
        out_data_hex_all.emp2016 AS emp2016,
        out_data_hex_all.business2016 AS business2016,
        out_data_hex_all.int3way AS int3way,
        out_data_hex_all.int4way AS int4way,
        out_data_hex_all.transit_n_per_hour AS transit_n_per_hour,
        out_data_hex_all.walk_edge_length AS walk_edge_length
        FROM weights_hex_da
        INNER JOIN out_data_hex_all ON out_data_hex_all.hexid = weights_hex_da.hexid
    ), temp_weight_sum AS (
        SELECT
        temp_weight_join.dauid AS dauid,
        SUM(temp_weight_join.weight * temp_weight_join.pop2016) AS pop2016,
        SUM(temp_weight_join.weight * temp_weight_join.emp2016) AS emp2016,
        SUM(temp_weight_join.weight * temp_weight_join.business2016) AS business2016,
        SUM(temp_weight_join.weight * temp_weight_join.int3way) AS int3way,
        SUM(temp_weight_join.weight * temp_weight_join.int4way) AS int4way,
        SUM(temp_weight_join.weight * temp_weight_join.transit_n_per_hour) AS transit_n_per_hour,
        SUM(temp_weight_join.weight * temp_weight_join.walk_edge_length) AS walk_edge_length
        FROM temp_weight_join GROUP BY temp_weight_join.dauid
    ) 
    SELECT
        temp_weight_sum.dauid AS dauid,
        temp_weight_sum.pop2016 AS pop2016,
        temp_weight_sum.emp2016 AS emp2016,
        temp_weight_sum.business2016 AS business2016,
        temp_weight_sum.int3way AS int3way,
        temp_weight_sum.int4way AS int4way,
        temp_weight_sum.transit_n_per_hour AS transit_n_per_hour,
        temp_weight_sum.walk_edge_length AS walk_edge_length,
        ST_Area(zones_da16.geom) / (1000 * 1000) AS area
    FROM temp_weight_sum LEFT JOIN zones_da16 ON zones_da16.dauid = temp_weight_sum.dauid
);

-- create density columns

ALTER TABLE out_data_da ADD COLUMN pop2016_D double precision;
UPDATE out_data_da SET pop2016_D = pop2016 / area;

ALTER TABLE out_data_da ADD COLUMN emp2016_D double precision;
UPDATE out_data_da SET emp2016_D = emp2016 / area;

ALTER TABLE out_data_da ADD COLUMN business2016_D double precision;
UPDATE out_data_da SET business2016_D = business2016 / area;

ALTER TABLE out_data_da ADD COLUMN int3way_D double precision;
UPDATE out_data_da SET int3way_D = int3way / area;

ALTER TABLE out_data_da ADD COLUMN int4way_D double precision;
UPDATE out_data_da SET int4way_D = int4way / area;

ALTER TABLE out_data_da ADD COLUMN transit_n_per_hour_D double precision;
UPDATE out_data_da SET transit_n_per_hour_D = transit_n_per_hour / area;

ALTER TABLE out_data_da ADD COLUMN walk_edge_length_D double precision;
UPDATE out_data_da SET walk_edge_length_D = walk_edge_length / area;

```

## Linking to 2016 traffic analysis zones (TAZ)

```sql
-- create spatial index on TAZ boundaries

DROP INDEX IF EXISTS zones_taz_gix;
CREATE INDEX zones_taz_gix ON zones_taz USING GIST (geom);

-- intersect the DA boundaries with the hex grid

CREATE TABLE temp_int_hex_da AS
(
SELECT
hex_grid_200m.id AS hexid,
zones_taz.gta06 AS gta06,
34641.0161513719 AS area_full,
ST_Intersection(hex_grid_200m.geom,ST_CollectionExtract(ST_MakeValid(zones_taz.geom),3)) AS geom
FROM
zones_taz INNER JOIN hex_grid_200m ON ST_Intersects(hex_grid_200m.geom,ST_CollectionExtract(ST_MakeValid(zones_taz.geom),3))
);

-- update area of intersected geoms

ALTER TABLE temp_int_hex_da ADD COLUMN area_int double precision;
UPDATE temp_int_hex_da SET area_int = ST_AREA(geom);

ALTER TABLE temp_int_hex_da ADD COLUMN area_ratio double precision;
UPDATE temp_int_hex_da SET area_ratio = area_int / area_full;

-- create weights table for apportioning

CREATE TABLE weights_hex_taz AS
(
SELECT
hexid,
gta06,
sum(area_ratio) AS weight
FROM
temp_int_hex_da
GROUP BY gta06, hexid
ORDER BY gta06, hexid
);

DROP TABLE temp_int_hex_da;

-- join data and apportion to boundaries

DROP TABLE IF EXISTS out_data_taz;
CREATE TABLE out_data_taz AS (
    WITH temp_weight_join AS (
        SELECT
        weights_hex_taz.gta06 AS gta06,
        weights_hex_taz.hexid AS hexid,
        weights_hex_taz.weight AS weight,
        out_data_hex_all.pop2016 AS pop2016,
        out_data_hex_all.emp2016 AS emp2016,
        out_data_hex_all.business2016 AS business2016,
        out_data_hex_all.int3way AS int3way,
        out_data_hex_all.int4way AS int4way,
        out_data_hex_all.transit_n_per_hour AS transit_n_per_hour,
        out_data_hex_all.walk_edge_length AS walk_edge_length
        FROM weights_hex_taz
        INNER JOIN out_data_hex_all ON out_data_hex_all.hexid = weights_hex_taz.hexid
    ), temp_weight_sum AS (
        SELECT
        temp_weight_join.gta06 AS gta06,
        SUM(temp_weight_join.weight * temp_weight_join.pop2016) AS pop2016,
        SUM(temp_weight_join.weight * temp_weight_join.emp2016) AS emp2016,
        SUM(temp_weight_join.weight * temp_weight_join.business2016) AS business2016,
        SUM(temp_weight_join.weight * temp_weight_join.int3way) AS int3way,
        SUM(temp_weight_join.weight * temp_weight_join.int4way) AS int4way,
        SUM(temp_weight_join.weight * temp_weight_join.transit_n_per_hour) AS transit_n_per_hour,
        SUM(temp_weight_join.weight * temp_weight_join.walk_edge_length) AS walk_edge_length
        FROM temp_weight_join GROUP BY temp_weight_join.gta06
    ) 
    SELECT
        temp_weight_sum.gta06 AS gta06,
        temp_weight_sum.pop2016 AS pop2016,
        temp_weight_sum.emp2016 AS emp2016,
        temp_weight_sum.business2016 AS business2016,
        temp_weight_sum.int3way AS int3way,
        temp_weight_sum.int4way AS int4way,
        temp_weight_sum.transit_n_per_hour AS transit_n_per_hour,
        temp_weight_sum.walk_edge_length AS walk_edge_length,
        ST_Area(zones_taz.geom) / (1000 * 1000) AS area
    FROM temp_weight_sum LEFT JOIN zones_taz ON zones_taz.gta06 = temp_weight_sum.gta06
);

-- create density columns

ALTER TABLE out_data_taz ADD COLUMN pop2016_D double precision;
UPDATE out_data_taz SET pop2016_D = pop2016 / area;

ALTER TABLE out_data_taz ADD COLUMN emp2016_D double precision;
UPDATE out_data_taz SET emp2016_D = emp2016 / area;

ALTER TABLE out_data_taz ADD COLUMN business2016_D double precision;
UPDATE out_data_taz SET business2016_D = business2016 / area;

ALTER TABLE out_data_taz ADD COLUMN int3way_D double precision;
UPDATE out_data_taz SET int3way_D = int3way / area;

ALTER TABLE out_data_taz ADD COLUMN int4way_D double precision;
UPDATE out_data_taz SET int4way_D = int4way / area;

ALTER TABLE out_data_taz ADD COLUMN transit_n_per_hour_D double precision;
UPDATE out_data_taz SET transit_n_per_hour_D = transit_n_per_hour / area;

ALTER TABLE out_data_taz ADD COLUMN walk_edge_length_D double precision;
UPDATE out_data_taz SET walk_edge_length_D = walk_edge_length / area;

-- output the data

\COPY out_data_taz TO 'out_data_TAZ2016.csv' WITH (FORMAT CSV, HEADER);

```